name: chat_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.3
  get: ^4.6.5
  http: ^0.13.5
  shared_preferences: ^2.0.15
  permission_handler: ^10.2.0
  socket_io_client: ^2.0.0
  contacts_service: ^0.6.3
  intl_phone_field: ^3.1.0
  chat_bubbles: ^1.3.1
  image_picker: ^0.8.5+3
  story_view: ^0.13.2
  objectbox: ^1.6.2
  objectbox_flutter_libs: any
  path_provider: ^2.0.11
  status_view: ^0.0.2
  cached_network_image: ^3.2.2
  font_awesome_flutter: ^10.2.1
  flutter_staggered_animations: ^1.0.0
  cupertino_icons: ^1.0.2
  json_serializable: ^6.3.1
  cloudinary_public: ^0.12.0
  device_info_plus: ^6.0.0
  badges: ^2.0.3
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  objectbox_generator: any
 


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/avatar.png    
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
